image: ubuntu:18.04

variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

.setup: &setup
  - apt update
  - apt install -y software-properties-common
  - apt-add-repository -y ppa:deadsnakes/ppa
  - apt update
  - apt install -y python3.7 python3-pip
  - python3.7 --version
  - pip3 install pipenv
  - pipenv --python=$(which python3.7) install -d

pages:
  tags:
    - linux
    - docker
    - build
  script:
    - *setup
    - pipenv run docs
    - mv docs/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

lint:
  tags:
    - linux
    - docker
    - build
  script:
    - *setup
    - pipenv run lint

typecheck:
  tags:
    - linux
    - docker
    - build
  script:
    - *setup
    - pipenv run typecheck

.dp-rule:
  rules:
    - if: '$CI_PROJECT_ROOT_NAMESPACE == "darpa_learn"'
      when: on_success
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success

sailon-pipelines:
  trigger:
    project: darpa-sail-on/sail-on-client
    strategy: depend
  extends: .dp-rule

learn-pipelines:
  trigger:
    project: darpa_learn/learn
    strategy: depend
  allow_failure: true
  extends: .dp-rule
