image: ubuntu:18.04

variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

.setup: &setup
  - apt update
  - apt install -y software-properties-common
  - apt-add-repository -y ppa:deadsnakes/ppa
  - apt update
  - apt install -y python3.7 python3-pip
  - python3.7 --version
  - pip3 install pipenv
  - pipenv --python=$(which python3.7) install -d

pages:
  tags:
    - linux
    - docker
    - build
  script:
    - *setup
    - pipenv run docs
    - mv docs/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

lint:
  tags:
    - linux
    - docker
    - build
  script:
    - *setup
    - pipenv run lint

typecheck:
  tags:
    - linux
    - docker
    - build
  script:
    - *setup
    - pipenv run typecheck

release:
  tags:
    - linux
    - docker
    - build
  #only:
    #- tags
    #- master
  script:
    - *setup
    - apt install -y git
    - export
    - pipenv run python setup.py sdist
