image: pytorch/pytorch:latest

pages:
  tags:
    - linux
    - docker
    - build
  script:
  - python --version
  - conda install -y sphinx sphinx_rtd_theme pandas scikit-learn
  - pip install m2r fire ubelt boto3
  - (cd docs && make html)
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

.python-setup: &python-setup
  - pip install pipenv
  - pipenv install -d

lint:
  tags:
    - linux
    - docker
    - build
  script:
    - *python-setup
    - pipenv run lint

typecheck:
  tags:
    - linux
    - docker
    - build
  script:
    - *python-setup
    - pipenv run typecheck
